//! PuTTY session importer (Phase 2).
//!
//! Parses PuTTY exports in two flavours:
//!   - `.reg` — `regedit /e` dumps of `HKCU\Software\SimonTatham\PuTTY\Sessions\…`
//!     (UTF-16LE when written by regedit on Windows, UTF-8 when generated by
//!     tools like KiTTY or `putty -export`).
//!   - KiTTY-style `.txt` — `Session\<path>\key=value` lines.
//!
//! PuTTY stores session names URL-encoded (`%XX`); folders are backslash path
//! segments. WinSSHTerm's own sessions live under `Sessions\WinSSHTerm\…` and
//! `Sessions\WinSSHTerm_ScriptRunner\…` and are skipped.
//!
//! Mapped values: `HostName`, `PortNumber`, `UserName`, `PublicKeyFile`,
//! `DetachedCertificate`, `X11Forwarding`, and the proxy set (`ProxyMethod`
//! 1=SOCKS4, 2=SOCKS5, 3=HTTP, 5=Local), `ProxyHost`, `ProxyPort`,
//! `ProxyUsername`, `ProxyTelnetCommand`.

use crate::model::Node;
use std::collections::HashMap;

/// One PuTTY session's key/value map plus its (unescaped) path segments.
struct RawSession {
    /// folder segments, then the leaf name, all percent-unescaped
    path: Vec<String>,
    values: HashMap<String, String>,
}

/* ------------------------------ helpers ------------------------------ */

fn hex_val(b: u8) -> Option<u8> {
    if b.is_ascii_digit() {
        Some(b - b'0')
    } else if (b'a'..=b'f').contains(&b) {
        Some(b - b'a' + 10)
    } else if (b'A'..=b'F').contains(&b) {
        Some(b - b'A' + 10)
    } else {
        None
    }
}

fn is_ascii_letter(b: u8) -> bool {
    b.is_ascii_lowercase() || b.is_ascii_uppercase()
}

/// `%XX`-unescape a PuTTY session-name path (URL-style percent encoding).
fn unescape_path(raw: &str) -> String {
    let src = raw.as_bytes();
    let mut out: Vec<u8> = Vec::new();
    let mut i = 0;
    while i < src.len() {
        if src[i] == b'%' && i + 2 < src.len()
            && let Some(h) = hex_val(src[i + 1])
            && let Some(l) = hex_val(src[i + 2]) {
                out.push((h << 4) | l);
                i += 3;
                continue;
            }
        out.push(src[i]);
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// Unescape a regedit string value: `\n \r \t \\ \" \xNN` sequences.
fn unescape_reg_value(raw: &str) -> String {
    let src = raw.as_bytes();
    let mut out: Vec<u8> = Vec::new();
    let mut i = 0;
    while i < src.len() {
        let b = src[i];
        if b == b'\\' && i + 1 < src.len() {
            let n = src[i + 1];
            match n {
                b'n' => { out.push(b'\n'); i += 2; continue; }
                b'r' => { out.push(b'\r'); i += 2; continue; }
                b't' => { out.push(b'\t'); i += 2; continue; }
                b'\\' => { out.push(b'\\'); i += 2; continue; }
                b'"' => { out.push(b'"'); i += 2; continue; }
                b'x' => {
                    if i + 3 < src.len()
                        && let Some(h) = hex_val(src[i + 2])
                        && let Some(l) = hex_val(src[i + 3]) {
                            out.push((h << 4) | l);
                            i += 4;
                            continue;
                        }
                    out.push(b'\\');
                    out.push(n);
                    i += 2;
                    continue;
                }
                _ => {
                    out.push(b'\\');
                    out.push(n);
                    i += 2;
                    continue;
                }
            }
        }
        out.push(b);
        i += 1;
    }
    String::from_utf8_lossy(&out).into_owned()
}

/// True for absolute Windows paths like `C:\keys\id.ppk` or `C:/keys/id.ppk`.
pub fn is_windows_path(p: &str) -> bool {
    let b = p.as_bytes();
    b.len() >= 3 && is_ascii_letter(b[0]) && b[1] == b':' && (b[2] == b'\\' || b[2] == b'/')
}

/// Strip one layer of surrounding double quotes, if both are present.
fn unquote(s: &str) -> String {
    let t = s.trim();
    if t.len() >= 2 && t.starts_with("\"") && t.ends_with("\"") {
        t[1..t.len() - 1].to_string()
    } else {
        t.to_string()
    }
}

/// Index of the last `Sessions` element in a registry section path (the marker
/// that precedes PuTTY session names), if any.
fn sessions_marker_idx(parts: &[String]) -> Option<usize> {
    let mut idx: Option<usize> = None;
    for (i, p) in parts.iter().enumerate() {
        if p.eq_ignore_ascii_case("Sessions") {
            idx = Some(i);
        }
    }
    idx
}

/// Join `parts[from..]` with `\` (PuTTY path separator).
fn join_from(parts: &[String], from: usize) -> String {
    let mut out = String::with_capacity(0);
    let mut first = true;
    let mut i = from;
    while i < parts.len() {
        if !first {
            out.push('\\');
        }
        out.push_str(&parts[i]);
        first = false;
        i += 1;
    }
    out
}

/* ------------------------------ line parsers ------------------------------ */

/// Parse a `"key"="value"` regedit line. The key/value are raw (still escaped).
fn parse_quoted_line(l: &str) -> Option<(String, String)> {
    let b = l.as_bytes();
    if b.len() < 2 || b[0] != b'"' {
        return None;
    }
    // key: from 1 to the matching close quote (backslash escapes the next char)
    let mut i = 1;
    let mut key_end: Option<usize> = None;
    while i < b.len() {
        if b[i] == b'\\' {
            i += 2;
            continue;
        }
        if b[i] == b'"' {
            key_end = Some(i);
            break;
        }
        i += 1;
    }
    let ke = key_end?;

    // expect `=` after optional spaces
    let mut j = ke + 1;
    while j < b.len() && b[j] == b' ' {
        j += 1;
    }
    if j >= b.len() || b[j] != b'=' {
        return None;
    }
    j += 1;
    while j < b.len() && b[j] == b' ' {
        j += 1;
    }

    let value: String;
    if j < b.len() && b[j] == b'"' {
        let mut k = j + 1;
        let mut val_end: Option<usize> = None;
        while k < b.len() {
            if b[k] == b'\\' {
                k += 2;
                continue;
            }
            if b[k] == b'"' {
                val_end = Some(k);
                break;
            }
            k += 1;
        }
        match val_end {
            Some(ve) => value = unescape_reg_value(&l[j + 1..ve]),
            None => value = String::with_capacity(0),
        }
    } else {
        value = unquote(&l[j..]);
    }

    Some((unescape_reg_value(&l[1..ke]), value))
}

/// Split a `path\key` lhs into its segments.
fn split_segments(s: &str) -> Vec<String> {
    let mut parts: Vec<String> = Vec::new();
    for seg in s.split("\\") {
        parts.push(seg.to_string());
    }
    parts
}

fn make_raw(raw_path: &str) -> RawSession {
    let unesc = unescape_path(raw_path);
    let mut path: Vec<String> = Vec::new();
    for seg in unesc.split("\\") {
        if !seg.is_empty() {
            path.push(seg.to_string());
        }
    }
    RawSession { path, values: HashMap::new() }
}

fn flush(sessions: &mut Vec<RawSession>, current: &mut Option<RawSession>) {
    if let Some(s) = current.take() {
        sessions.push(s);
    }
}

/* ------------------------------ main parse ------------------------------ */

/// Parse `.reg` / KiTTY `.txt` text into a merged session tree plus warnings.
pub fn import_text(text: &str) -> (Vec<Node>, Vec<String>) {
    let mut sessions: Vec<RawSession> = Vec::new();
    let mut current: Option<RawSession> = None;

    for line in text.split("\n") {
        let l = line.trim();
        if l.is_empty() {
            continue;
        }

        // Registry section header: [HKEY_...\PuTTY\Sessions\<path>]
        if l.starts_with("[") && l.ends_with("]") {
            flush(&mut sessions, &mut current);
            let inner = &l[1..l.len() - 1];
            let mut parts: Vec<String> = Vec::new();
            for seg in inner.split("\\") {
                parts.push(seg.to_string());
            }
            if let Some(k) = sessions_marker_idx(&parts)
                && parts.len() > k + 1 {
                    current = Some(make_raw(&join_from(&parts, k + 1)));
                } else {
                    current = None;
                }
            continue;
        }

        // regedit value line: "key"="value"
        if l.starts_with("\"") && let Some((k, v)) = parse_quoted_line(l) {
            if let Some(ref mut s) = current {
                s.values.insert(k, v);
            }
            continue;
        }

        // KiTTY txt: Session\<path>\<key>=<value>
        if l.len() >= 8 && l.to_ascii_uppercase().starts_with("SESSION\\") {
            let rest = &l[8..];
            match rest.find("=") {
                None => {
                    current = Some(make_raw(rest));
                }
                Some(eqi) => {
                    let lhs = &rest[..eqi];
                    let rhs = unquote(&rest[eqi + 1..]);
                    let parts = split_segments(lhs);
                    if parts.len() >= 2 {
                        let ps = &parts[..parts.len() - 1];
                        let key = parts[parts.len() - 1].clone();
                        let path = join_from(ps, 0);
                        let new = make_raw(&path);
                        // Same session path as the current one → extend it;
                        // otherwise close the current session and start this one.
                        let mut same_path = false;
                        if let Some(ref s) = current {
                            same_path = s.path == new.path;
                        }
                        if same_path {
                            if let Some(ref mut s) = current {
                                s.values.insert(key, rhs);
                            }
                            continue;
                        }
                        flush(&mut sessions, &mut current);
                        current = Some(new);
                        if let Some(ref mut s) = current {
                            s.values.insert(key, rhs);
                        }
                    } else {
                        current = Some(make_raw(lhs));
                    }
                }
            }
            continue;
        }

        // Loose key=value continuation lines (KiTTY edge cases).
        if let Some(eqi) = l.find("=") {
            if let Some(ref mut s) = current {
                let k = l[..eqi].trim();
                let v = unquote(&l[eqi + 1..]);
                s.values.insert(k.to_string(), v);
            }
            continue;
        }
    }
    flush(&mut sessions, &mut current);

    let mut warnings: Vec<String> = Vec::new();
    let nodes = sessions_to_nodes(&sessions, &mut warnings);
    (nodes, warnings)
}

/* ------------------------------ mapping ------------------------------ */

fn get_key(s: &RawSession, key: &str) -> String {
    s.values
        .iter()
        .find(|(k, _)| k.eq_ignore_ascii_case(key))
        .map(|(_, v)| v.clone())
        .unwrap_or_default()
}

fn warn_windows_path(warnings: &mut Vec<String>, session: &str, what: &str, value: &str) {
    if !value.is_empty() && is_windows_path(value) {
        warnings.push(format!(
            "Session '{session}': {what} '{value}' is a Windows path — set the Linux key path after import."
        ));
    }
}

fn map_proxy(s: &RawSession, node: &mut Node, leaf: &str, warnings: &mut Vec<String>) {
    let method = get_key(s, "ProxyMethod");
    if method.is_empty() || method == "0" {
        // no proxy
        return;
    }
    if method == "1" {
        node.proxy_type = "SOCKS4".into();
    } else if method == "2" {
        node.proxy_type = "SOCKS5".into();
    } else if method == "3" {
        node.proxy_type = "HTTP".into();
    } else if method == "5" {
        node.proxy_type = "Local".into();
        node.proxy_telnet_cmd = get_key(s, "ProxyTelnetCommand");
    } else {
        warnings.push(format!(
            "Session '{leaf}': unsupported ProxyMethod {method} ignored — no proxy mapping."
        ));
        return;
    }

    node.proxy_host = get_key(s, "ProxyHost");
    if node.proxy_host.is_empty() {
        // PuTTY says "use a proxy" but no host is configured — treat as off.
        node.proxy_enabled = false;
        node.proxy_type = "".into();
        return;
    }
    node.proxy_enabled = true;
    node.proxy_port = get_key(s, "ProxyPort");
    node.proxy_user = get_key(s, "ProxyUsername");
}

fn session_node(s: &RawSession, warnings: &mut Vec<String>) -> Node {
    let mut leaf: String = String::with_capacity(0);
    for seg in &s.path {
        leaf = seg.clone();
    }
    let host = get_key(s, "HostName");
    let user = get_key(s, "UserName");
    let port_str = get_key(s, "PortNumber");
    let port: u16 = if port_str.is_empty() {
        22
    } else {
        port_str.parse::<u16>().unwrap_or(22)
    };

    let mut node = Node::connection(&leaf, &host, &user, port);
    node.private_key = get_key(s, "PublicKeyFile");
    node.certificate = get_key(s, "DetachedCertificate");
    if get_key(s, "X11Forwarding").eq_ignore_ascii_case("yes") {
        node.x11 = "yes".into();
    }

    map_proxy(s, &mut node, &leaf, warnings);
    warn_windows_path(warnings, &leaf, "PrivateKey", &node.private_key);
    warn_windows_path(warnings, &leaf, "Certificate", &node.certificate);
    node
}

fn is_winsshterm(path: &[String]) -> bool {
    !path.is_empty()
        && (path[0].eq_ignore_ascii_case("WinSSHTerm")
            || path[0].eq_ignore_ascii_case("WinSSHTerm_ScriptRunner"))
}

fn container_index(nodes: &[Node], name: &str) -> Option<usize> {
    for (i, n) in nodes.iter().enumerate() {
        if n.name == name && n.is_container() {
            return Some(i);
        }
    }
    None
}

/// Insert `leaf` into the node forest at the path `segs` (creating containers).
fn insert_path(nodes: &mut Vec<Node>, segs: Vec<String>, leaf: Node) {
    if segs.len() <= 1 {
        nodes.push(leaf);
        return;
    }
    let mut head: String = String::with_capacity(0);
    if let Some(seg) = segs.first() {
        head = seg.clone();
    }
    match container_index(nodes, &head) {
        Some(i) => {
            let mut kids = nodes[i].children.to_vec();
            insert_path(&mut kids, segs[1..].to_vec(), leaf);
            nodes[i].children = kids;
        }
        None => {
            let mut kids: Vec<Node> = Vec::new();
            insert_path(&mut kids, segs[1..].to_vec(), leaf);
            nodes.push(Node::container(&head, true).with_children(kids));
        }
    }
}

fn sessions_to_nodes(sessions: &[RawSession], warnings: &mut Vec<String>) -> Vec<Node> {
    let mut roots: Vec<Node> = Vec::new();
    for s in sessions {
        if s.path.is_empty() || is_winsshterm(&s.path) {
            continue;
        }
        let node = session_node(s, warnings);
        insert_path(&mut roots, s.path.to_vec(), node);
    }
    roots
}

/* ------------------------------ tests ------------------------------ */

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::KIND_CONTAINER;

    fn reg_sample() -> String {
        "Windows Registry Editor Version 5.00\n\
\n[HKEY_CURRENT_USER\\Software\\SimonTatham\\PuTTY\\Sessions\\Proxmox%20Hosts\\elitedesk%20one]\n\"HostName\"=\"192.168.100.201\"\n\"PortNumber\"=\"22\"\n\"UserName\"=\"root\"\n\"PublicKeyFile\"=\"C:\\\\keys\\\\id_ed25519.ppk\"\n\"X11Forwarding\"=\"yes\"\n\"ProxyMethod\"=\"2\"\n\"ProxyHost\"=\"proxy.local\"\n\"ProxyPort\"=\"1080\"\n\"ProxyUsername\"=\"sam\"\n\
\n[HKEY_CURRENT_USER\\Software\\SimonTatham\\PuTTY\\Sessions\\WinSSHTerm\\somewhere]\n\"HostName\"=\"10.1.2.3\"\n\
\n[HKEY_CURRENT_USER\\Software\\SimonTatham\\PuTTY\\Sessions\\plain%20host]\n\"HostName\"=\"10.0.0.5\"\n\"PortNumber\"=\"2222\"\n\"UserName\"=\"sam\"\n".to_string()
    }

    fn kitty_sample() -> String {
        "# KiTTY session export\n\
Session\\Beleaf\\Prod%20DB\\HostName=10.9.9.9\n\
Session\\Beleaf\\Prod%20DB\\PortNumber=5432\n\
Session\\Beleaf\\Prod%20DB\\UserName=postgres\n\
Session\\Beleaf\\Prod%20DB\\PublicKeyFile=/home/user/.ssh/id_ed25519\n".to_string()
    }

    fn has_warning(warnings: &[String], needle: &str) -> bool {
        for w in warnings {
            if w.find(needle).is_some() {
                return true;
            }
        }
        false
    }

    #[test]
    fn parses_reg_sections_and_values() {
        let (nodes, _) = import_text(&reg_sample());
        // WinSSHTerm session is skipped
        assert_eq!(nodes.len(), 2);

        let folder = &nodes[0];
        assert_eq!(folder.name, "Proxmox Hosts");
        assert_eq!(folder.node_type, KIND_CONTAINER);
        assert_eq!(folder.children.len(), 1);

        let one = &folder.children[0];
        assert_eq!(one.name, "elitedesk one");
        assert_eq!(one.hostname, "192.168.100.201");
        assert_eq!(one.username, "root");
        assert_eq!(one.port, "22");
        assert_eq!(one.private_key, "C:\\keys\\id_ed25519.ppk");
        assert_eq!(one.x11, "yes");
        assert!(one.proxy_enabled);
        assert_eq!(one.proxy_type, "SOCKS5");
        assert_eq!(one.proxy_host, "proxy.local");
        assert_eq!(one.proxy_port, "1080");
        assert_eq!(one.proxy_user, "sam");

        let plain = &nodes[1];
        assert_eq!(plain.name, "plain host");
        assert_eq!(plain.hostname, "10.0.0.5");
        assert_eq!(plain.port, "2222");
        assert!(!plain.proxy_enabled);
    }

    #[test]
    fn warns_on_windows_key_paths() {
        let (_, warnings) = import_text(&reg_sample());
        assert!(has_warning(&warnings, "Windows path"));
        assert!(has_warning(&warnings, "id_ed25519.ppk"));
    }

    #[test]
    fn parses_kitty_txt() {
        let (nodes, _) = import_text(&kitty_sample());
        assert_eq!(nodes.len(), 1);
        let folder = &nodes[0];
        assert_eq!(folder.name, "Beleaf");
        assert_eq!(folder.children.len(), 1);
        let db = &folder.children[0];
        assert_eq!(db.name, "Prod DB");
        assert_eq!(db.hostname, "10.9.9.9");
        assert_eq!(db.port, "5432");
        assert_eq!(db.username, "postgres");
        assert_eq!(db.private_key, "/home/user/.ssh/id_ed25519");
    }

    #[test]
    fn percent_decodes_names() {
        assert_eq!(unescape_path("hello%20world%2Fv2"), "hello world/v2");
        assert_eq!(unescape_path("plain"), "plain");
    }

    #[test]
    fn reg_value_escapes() {
        assert_eq!(unescape_reg_value("a\\tb\\n\\\"q\\\"\\\\z"), "a\tb\n\"q\"\\z");
        assert_eq!(unescape_reg_value("\\x41"), "A");
    }

    #[test]
    fn windows_path_detection() {
        assert!(is_windows_path("C:\\keys\\id.ppk"));
        assert!(is_windows_path("d:/x"));
        assert!(!is_windows_path("/home/user/.ssh/id_ed25519"));
        assert!(!is_windows_path("~/.ssh/key.pem"));
    }

    #[test]
    fn maps_local_proxy_method() {
        let (nodes, _) = import_text(
            "[HKEY_CURRENT_USER\\Software\\SimonTatham\\PuTTY\\Sessions\\tun]\n\"HostName\"=\"10.1.1.1\"\n\"ProxyMethod\"=\"5\"\n\"ProxyHost\"=\"jump.example\"\n\"ProxyTelnetCommand\"=\"nc %host %port\"\n",
        );
        assert_eq!(nodes.len(), 1);
        let n = &nodes[0];
        assert!(n.proxy_enabled);
        assert_eq!(n.proxy_type, "Local");
        assert_eq!(n.proxy_telnet_cmd, "nc %host %port");
    }

    #[test]
    fn unsupported_proxy_method_warns() {
        let (nodes, warnings) = import_text(
            "[HKEY_CURRENT_USER\\Software\\SimonTatham\\PuTTY\\Sessions\\weird]\n\"HostName\"=\"10.1.1.1\"\n\"ProxyMethod\"=\"4\"\n",
        );
        assert_eq!(nodes.len(), 1);
        assert!(!nodes[0].proxy_enabled);        assert!(has_warning(&warnings, "ProxyMethod 4"));
    }
}